### ISSUE TITLE
WikiContrib violates user privacy by loading third party content from Cloudflare

### ISSUE THREAD

**Issue by aklapper** [wikimedia/WikiContrib#279]
https://wikicontrib.toolforge.org/ loads `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">`. This is a third-party privacy violation.

It's more concerning now that this tool is linked from the Wikimedia Developer Portal.

Please use https://tools-static.wmflabs.org/cdnjs/ajax/libs/semantic-ui/2.4.1/semantic.min.css instead and deploy.

See also https://phabricator.wikimedia.org/T231312

**Comment by srish** [comment]
@NdibeRaymond You still have access to this tool on Toolforge right? I'd let you take on this.

**Comment by aklapper** [comment]
https://toolsadmin.wikimedia.org/tools/id/wikicontrib lists four maintainers :)

**Comment by NdibeRaymond** [comment]
> @NdibeRaymond You still have access to this tool on Toolforge right? I'd let you take on this.

yes I still do @srish. I will fix this issue

**Comment by NdibeRaymond** [comment]
> https://wikicontrib.toolforge.org/ loads `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">`. This is a third-party privacy violation.
> 
> It's more concerning now that this tool is linked from the Wikimedia Developer Portal.
> 
> Please use https://tools-static.wmflabs.org/cdnjs/ajax/libs/semantic-ui/2.4.1/semantic.min.css instead and deploy.
> 
> See also https://phabricator.wikimedia.org/T231312

thanks for making this known @aklapper . I will fix this ASAP

**Comment by wkyoshida** [comment]
Hi!

Out of curiosity - I was wondering if this issue has now been resolved with https://github.com/wikimedia/WikiContrib/pull/280 - would that be right?

**Comment by aklapper** [comment]
That's a good question for @NdibeRaymond - if this is fixed, please close this ticket

**Comment by NdibeRaymond** [comment]
Yeaaa forgot to close this, closing now

**Comment by aklapper** [comment]
This is still an issue when I go to https://wikicontrib.toolforge.org/ - how was this resolved? If this was resolved, do you plan to deploy the changes?

**Comment by aklapper** [comment]
@NdibeRaymond This is still an issue when I go to https://wikicontrib.toolforge.org/ - how was this resolved? If this was resolved, do you plan to deploy the changes?
